[template]
# prefix = "pgbouncer"
owner = "postgres"
mode = "0644"
src = "pgbouncer.tmpl"
dest = "/etc/pgbouncer/pgbouncer.ini"

reload_cmd = "/usr/sbin/pgbouncer -Rd /etc/pgbouncer/pgbouncer.ini"

keys = [
    "/members/","/leader"
]